### ISSUE TITLE
Reorganize the repository to add unit-test

### ISSUE THREAD

**Issue by SaidAlvarado** [SaidAlvarado/LH2-3D-accuracy-experiment#1]
Goals:
- Separate dataset generation and dataset processing into different scripts.
- Divide the data processing script into individual functions.
- Reorganize the folders to put data generation and data processing into different folders.
- Have separate folders for real data and simulated data

**Comment by SaidAlvarado** [comment]
TO-DO:
- Update the ReadMe
- Modify the simulated data script to generate a csv instead of processing the data directly

**Comment by twatteyne** [comment]
great! some further points:
- no spaces in folder names: `dataset_experimental`, `dataset_synthetic`
- `main` is a keyword in Python. give you approach a name. lh3d? rename file to that
- update the `README.md` with short instructions which allow me to run something on my computer and see some results

After I'm able to run something, we will talk about the contents of the files.

**Comment by SaidAlvarado** [comment]
@twatteyne Thanks for the suggestions!
All comments have been addressed. Looking forward to further feedback.

**Comment by twatteyne** [comment]
I'm closing as this is replaced by #3.
